In [2]:
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np

## Data Generation

In [3]:
observations = 1000

xs = np.random.uniform(low=-10, high=10, size=(observations,1))
zs = np.random.uniform(low=-10, high=10, size=(observations,1))

generated_inputs = np.column_stack((xs,zs))

noise = np.random.uniform(-1,1,(observations,1))
generated_targets = 2*xs - 3*zs + 5 + noise

np.savez('TF_intro',inputs=generated_inputs,targets=generated_targets)

## Solving with TensorFlow

In [4]:
training_data = np.load('TF_intro.npz')

In [5]:
input_size = 2
output_size = 1

model = tf.keras.Sequential([
    tf.keras.layers.Dense(output_size)                                         
])

custom_optimizer = tf.keras.optimizers.SGD(learning_rate=0.02)

model.compile(optimizer=custom_optimizer,loss='mean_squared_error')
model.fit(training_data['inputs'],training_data['targets'],epochs=100, verbose=2)

Epoch 1/100
32/32 - 1s - loss: 26.8704 - 791ms/epoch - 25ms/step
Epoch 2/100
32/32 - 0s - loss: 1.0683 - 48ms/epoch - 1ms/step
Epoch 3/100
32/32 - 0s - loss: 0.3994 - 47ms/epoch - 1ms/step
Epoch 4/100
32/32 - 0s - loss: 0.3427 - 49ms/epoch - 2ms/step
Epoch 5/100
32/32 - 0s - loss: 0.3340 - 51ms/epoch - 2ms/step
Epoch 6/100
32/32 - 0s - loss: 0.3685 - 49ms/epoch - 2ms/step
Epoch 7/100
32/32 - 0s - loss: 0.3613 - 48ms/epoch - 1ms/step
Epoch 8/100
32/32 - 0s - loss: 0.3645 - 64ms/epoch - 2ms/step
Epoch 9/100
32/32 - 0s - loss: 0.3687 - 68ms/epoch - 2ms/step
Epoch 10/100
32/32 - 0s - loss: 0.3634 - 55ms/epoch - 2ms/step
Epoch 11/100
32/32 - 0s - loss: 0.3478 - 65ms/epoch - 2ms/step
Epoch 12/100
32/32 - 0s - loss: 0.4147 - 53ms/epoch - 2ms/step
Epoch 13/100
32/32 - 0s - loss: 0.3716 - 50ms/epoch - 2ms/step
Epoch 14/100
32/32 - 0s - loss: 0.3595 - 49ms/epoch - 2ms/step
Epoch 15/100
32/32 - 0s - loss: 0.4078 - 56ms/epoch - 2ms/step
Epoch 16/100
32/32 - 0s - loss: 0.3645 - 61ms/epoch - 2ms/ste

## Extract the weights and bias

In [6]:
model.layers[0].get_weights()

[array([[ 1.9010322],
        [-3.0410573]], dtype=float32),
 array([5.0418878], dtype=float32)]

## Prediction

In [7]:
model.predict_on_batch(training_data['inputs']).round(1)

array([[-18.2],
       [ -4.5],
       [-12.7],
       [  1.9],
       [-18.3],
       [-11.3],
       [ -1.2],
       [ -1.1],
       [ 18.7],
       [-30.2],
       [-39.9],
       [ 47.5],
       [ 19.5],
       [-24. ],
       [ 19.7],
       [ 14.6],
       [  2.2],
       [  4. ],
       [ 20.2],
       [ -2.8],
       [ 19.9],
       [ 36.8],
       [ 22.9],
       [ 31.1],
       [  4.6],
       [ -0.1],
       [ 13. ],
       [ -6.7],
       [-31.4],
       [ 26. ],
       [  6.5],
       [-10. ],
       [-35.8],
       [ 10.7],
       [ -5.2],
       [-23.9],
       [ 31.9],
       [-11.1],
       [  4.3],
       [  9.4],
       [ 10.3],
       [ 11.2],
       [  1. ],
       [ 27.9],
       [ 35.5],
       [  9.2],
       [ 37.1],
       [-15.2],
       [-18.3],
       [ 31.7],
       [ 27.7],
       [  7.5],
       [ 21.9],
       [-22.8],
       [-25.6],
       [-30. ],
       [ 32.3],
       [-24.4],
       [ 14.8],
       [-29.4],
       [ -1.7],
       [ 12.6],
       [

In [8]:
training_data['inputs'].round(1)

array([[-7.8,  2.8],
       [ 2.8,  4.9],
       [ 6.7, 10. ],
       ...,
       [ 6.3,  1.6],
       [ 2.8, -8.6],
       [-6.6, -9.3]])

In [ ]:
plt.plot(np.squeeze(model.predict_on_batch(training_data['inputs'])), np.squeeze(training_data['targets']))
plt.xlabel('outputs')
plt.ylabel('targets')
plt.show()